#!/usr/bin/env bash
# Re-apply our refs-only navstack customizations onto a Navigation-Physical-Experiment clone.
#
# WHY THIS EXISTS: refs/Navigation-Physical-Experiment is a git-ignored vendored dep (a clone
# of our upstream fork Yuxin916/Navigation-Physical-Experiment @ jazzy). We customized it in
# several layers, and a FRESH clone on a new machine reverts them all -> the digital twin
# regresses. Three distinct mechanisms keep those customizations; this script is the THIRD:
#
#   1. patch_navstack.sh  — Isaac-sim adaptation (use_sim_time everywhere, system_isaac_sim*
#      launch generation, kAutoStart false, ...). Regenerated by sed/python transforms on the
#      pristine clone. RUN THIS FIRST (user-manual step 2).
#   2. sync_navstack_files.sh — files whose TRUE SOURCE lives in scripts/nav/ (SLAM extrinsics
#      livox_mid360{,_calibration}.yaml incl. sensor_mount_pitch_deg=20 + use_sim_time, plus
#      agent_bridge/run_navstack/pc2_to_livox/...). Copied in by patch_navstack.sh and again
#      before every container start. NOTHING here overlaps those files.
#   3. THIS script — customizations that exist ONLY as direct edits inside the refs clone and
#      are reproduced by NEITHER mechanism above. See manifest.md for the exhaustive
#      sync-vs-patch file ownership (the two sets are mutually exclusive and jointly cover
#      every customization).
#
# The patch set (all base = the POST-patch_navstack pristine clone, so they compose on top):
#   01_sensor_mount_pitch_deg.patch     imuPreintegration.cpp: sensor_mount_pitch_deg param
#                                       (C++ half of commit 36b8e1b; its two yaml halves are
#                                       covered by sync #2, so they are NOT re-patched here).
#   02_local_planner_obstacleHeightThre.patch  local_planner.launch: obstacleHeightThre
#                                       0.05->0.20 (fix-c terrain-cost flicker root-cause).
#                                       DELIBERATELY EXCLUDES the fix-a groupSwitchRatio param
#                                       (active WIP owned by another session; C++ default
#                                       1.0=off makes its absence behaviorally identical).
#   03_arize_slam_respawn.patch         arize_slam.launch.py: respawn=True on the 3 SLAM nodes.
#
# Idempotent: each patch is reverse-checked and skipped if already applied. Also safe by hand.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$HERE/../../.." && pwd)"                       # go2w main repo root
NAV="${1:-$REPO_DIR/refs/Navigation-Physical-Experiment}"     # navstack clone (override arg 1)

if [ ! -d "$NAV/src/base_autonomy" ]; then
  echo "[nav-patch] ERROR: navstack clone not found under $NAV" >&2
  echo "[nav-patch] clone it + run scripts/nav/patch_navstack.sh FIRST (user-manual step 2)." >&2
  exit 1
fi

# Guard: these patches assume patch_navstack.sh already ran (use_sim_time present). If the
# clone is still pristine, the launch patches would fail their context match — fail loud.
if ! grep -q "use_sim_time" "$NAV/src/base_autonomy/local_planner/launch/local_planner.launch" 2>/dev/null; then
  echo "[nav-patch] ERROR: local_planner.launch has no use_sim_time — patch_navstack.sh has" >&2
  echo "[nav-patch] not been run on $NAV. Run it first, then re-run this script." >&2
  exit 1
fi

cd "$NAV"
apply_one() {
  local patch="$HERE/$1"
  local label="$2"
  if git apply --reverse --check "$patch" >/dev/null 2>&1; then
    echo "[nav-patch] already applied — skipping: $label"
  elif git apply --check "$patch" >/dev/null 2>&1; then
    git apply "$patch"
    echo "[nav-patch] applied: $label"
  else
    echo "[nav-patch] ERROR: patch does not apply cleanly: $label" >&2
    echo "[nav-patch] inspect: git -C $NAV apply --check $patch" >&2
    echo "[nav-patch] (did patch_navstack.sh run? is the clone at upstream jazzy tip?)" >&2
    exit 1
  fi
}

apply_one 01_sensor_mount_pitch_deg.patch          "imuPreintegration.cpp sensor_mount_pitch_deg (36b8e1b C++ half)"
apply_one 02_local_planner_obstacleHeightThre.patch "local_planner.launch obstacleHeightThre 0.20 (fix-c; fix-a excluded)"
apply_one 03_arize_slam_respawn.patch              "arize_slam.launch.py respawn on 3 SLAM nodes"

echo ""
echo "[nav-patch] DONE. Customizations re-applied to $NAV."
echo "[nav-patch] ---------------------------------------------------------------------------"
echo "[nav-patch] REBUILD NEEDED (in the jazzy-dev/navstack:ready container):"
echo "[nav-patch]   arise_slam_mid360  — patch 01 edits C++ (imuPreintegration.cpp), and this"
echo "[nav-patch]     package is in the documented build's --packages-skip, so navstack:ready"
echo "[nav-patch]     ships it UN-rebuilt. Rebuild it once (~62s precedent, DEBUG_extrinsic_friction.md):"
echo "[nav-patch]"
echo "[nav-patch]       docker run --rm --memory 8g -v $NAV:/ws -w /ws navstack:ready bash -c \\"
echo "[nav-patch]         'source /opt/ros/jazzy/setup.bash && colcon build --packages-select arise_slam_mid360'"
echo "[nav-patch]"
echo "[nav-patch]   Then re-commit the image (docker commit) if you want it baked into navstack:ready."
echo "[nav-patch]   Patches 02/03 are launch files only (no compile); a container restart suffices."
echo "[nav-patch] ---------------------------------------------------------------------------"
