#!/usr/bin/env python3
"""Generate go2w_bare.urdf from go2w_sensored.urdf by stripping the deployment payload.

WHY: the A/B judgement experiment (confirm the fault is OOD payload, not the policy itself)
needs a BARE control body — the ~6.92 kg trunk the policy was TRAINED on — vs the loaded
deployment body. Hand-copying two URDFs would drift; this derives the bare one from the
sensored one so they stay in lockstep. Re-run whenever go2w_sensored.urdf changes.

WHAT IS STRIPPED (the ~6.5 kg front-offset payload + its mounts/sensors that ride on it):
  - piper_* arm subtree (piper_base_link .. piper_link8, gripper)         ~4.66 kg
  - nuc_weight, mount_plate, regulator                                     NUC/compute/mounts
  - d435_link (hangs off the gripper -> orphaned once the arm is gone)     hand-eye camera
WHAT IS KEPT (the trained bare morphology — locomotion + head + body-mounted sensors):
  - base, all leg/wheel chains (FL/FR/RL/RR), Head_upper/lower, imu, radar, mid360_link

The kept set is exactly the 16-DOF locomotion body (12 leg + 4 wheel joints) the policy's
obs57/act16 covers; mid360/imu/radar are near-massless sensor frames on the base.

Usage:
    python3 scripts/sim/make_bare_urdf.py \
        [--in assets/urdf/go2w_sensored.urdf] [--out assets/urdf/go2w_bare.urdf]
"""
import argparse
import os
import xml.etree.ElementTree as ET

# Subtree ROOTS to remove (their descendants are pruned transitively). These are the child
# links of the fixed joints that attach the payload to base (+ d435 which rides the gripper).
PAYLOAD_ROOTS = {
    "piper_base_link",   # whole arm subtree
    "nuc_weight",
    "mount_plate",
    "regulator",
    "d435_link",         # child of piper_gripper_base -> would orphan; strip explicitly too
}


def build_child_map(root):
    """joint parent-link -> list of (joint_elem, child_link)."""
    children = {}
    for joint in root.findall("joint"):
        par = joint.find("parent")
        ch = joint.find("child")
        if par is None or ch is None:
            continue
        children.setdefault(par.get("link"), []).append((joint, ch.get("link")))
    return children


def collect_removable(root):
    """Return (links_to_remove, joints_to_remove) — the payload roots + all descendants."""
    children = build_child_map(root)
    remove_links = set()
    frontier = list(PAYLOAD_ROOTS)
    while frontier:
        link = frontier.pop()
        if link in remove_links:
            continue
        remove_links.add(link)
        for _joint, child in children.get(link, []):
            frontier.append(child)
    # any joint whose parent OR child is a removed link is removed
    remove_joints = set()
    for joint in root.findall("joint"):
        par = joint.find("parent")
        ch = joint.find("child")
        pl = par.get("link") if par is not None else None
        cl = ch.get("link") if ch is not None else None
        if (pl in remove_links) or (cl in remove_links):
            remove_joints.add(joint)
    return remove_links, remove_joints


def main():
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    ap.add_argument("--in", dest="inp", default=os.path.join(repo, "assets/urdf/go2w_sensored.urdf"))
    ap.add_argument("--out", dest="out", default=os.path.join(repo, "assets/urdf/go2w_bare.urdf"))
    args = ap.parse_args()

    tree = ET.parse(args.inp)
    root = tree.getroot()

    remove_links, remove_joints = collect_removable(root)

    # remove joints first, then links
    for joint in list(root.findall("joint")):
        if joint in remove_joints:
            root.remove(joint)
    kept_links = []
    for link in list(root.findall("link")):
        if link.get("name") in remove_links:
            root.remove(link)
        else:
            kept_links.append(link.get("name"))

    # sanity: exactly the 16 locomotion joints must survive
    surviving_joints = [j.get("name") for j in root.findall("joint")]
    leg_wheel = [j for j in surviving_joints
                 if j.endswith("_hip_joint") or j.endswith("_thigh_joint")
                 or j.endswith("_calf_joint") or j.endswith("_foot_joint")]
    assert len(leg_wheel) == 16, f"expected 16 leg/wheel joints, got {len(leg_wheel)}: {leg_wheel}"
    for pj in ("piper_joint1", "piper_joint7", "nuc_weight_joint"):
        assert pj not in surviving_joints, f"payload joint {pj} survived — stripper is wrong"

    # header comment (ET drops comments; prepend manually after write)
    tree.write(args.out, encoding="unicode", xml_declaration=True)
    header = (
        "<!-- AUTO-GENERATED by scripts/sim/make_bare_urdf.py from go2w_sensored.urdf. "
        "DO NOT hand-edit. Bare trunk (no PiPER arm / NUC / mounts / d435) = the body the "
        "shipped policy was TRAINED on; used as the A=bare control in the OOD A/B experiment. -->\n"
    )
    with open(args.out) as f:
        body = f.read()
    # insert header after the xml declaration line
    lines = body.split("\n", 1)
    with open(args.out, "w") as f:
        f.write(lines[0] + "\n" + header + (lines[1] if len(lines) > 1 else ""))

    print(f"[make_bare] wrote {args.out}")
    print(f"[make_bare] kept {len(kept_links)} links, {len(surviving_joints)} joints "
          f"({len(leg_wheel)} leg/wheel). stripped links: {sorted(remove_links)}")


if __name__ == "__main__":
    main()
